version: '2'
services:
  bitcoind:
    image: simplecoin/bitcoind:v0.21.0
    command: [
      "-testnet",
      "-rpcallowip=::/0",
      "-rpcuser=test",
      "-rpcpassword=test",
    ]
    environment:
      - DISABLEWALLET=0
  exporter:
    build: .
    ports:
      - "9439:9439"
    links:
      - bitcoind